[package]
name = "workers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
rand = "0.8.5"
tokio = { version = "1.41.0", features = ["sync", "rt", "rt-multi-thread", "macros", "time"]}
